#:schema node_modules/wrangler/config-schema.json
name = "top-streaming-services-portugal"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 0,8,12,17 * * *"]

[[env.production.vars]]
name = "ENVIRONMENT"
value = "production"

[[env.staging.vars]]
name = "ENVIRONMENT"
value = "staging"

[vars]
ENVIRONMENT = "development"

# Secrets (to be set via wrangler secret put)
# CLIENT_ID
# ACCESS_TOKEN
# REFRESH_TOKEN
# CLIENT_SECRET
# KIDS_LIST
# PRINT_LISTS