name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'wrangler.toml'
      - 'package.json'
      - '.github/workflows/cloudflare-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            CLIENT_ID
            ACCESS_TOKEN
            REFRESH_TOKEN
            CLIENT_SECRET
            GITHUB_TOKEN
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          KIDS_LIST: ${{ vars.KIDS_LIST }}
          PRINT_LISTS: ${{ vars.PRINT_LISTS }}