name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Check code formatting with Black
        run: |
          black --check --line-length 120 --target-version py312 top_pt_stream_services.py

      - name: Check code style with flake8
        run: |
          flake8 top_pt_stream_services.py --max-line-length=120

      - name: Check security issues with bandit
        run: |
          bandit -r top_pt_stream_services.py

      - name: Check import sorting with isort
        run: |
          isort --check-only --profile black --line-length 120 top_pt_stream_services.py

      - name: Type checking with mypy (if applicable)
        run: |
          # Skip mypy for now as it needs proper configuration
          echo "Skipping mypy - would need proper configuration for external libraries"

      - name: Test code compilation
        run: |
          python -m py_compile top_pt_stream_services.py